name: Block ads update

on:
  schedule:
    - cron: '0 0 * * *' # Chạy vào 00:00 mỗi ngày
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  block_ads_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install utilities
        run: sudo apt-get install -y jq curl

      - name: Run sync script
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        run: |
          chmod +x block_ads.sh
          ./block_ads.sh

      - name: Silent Git Commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add domain_list.txt || true
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update domains list" && git push origin HEAD) || true
